###Get all users
GET http://localhost:3001/user



### Get user data
GET http://localhost:3001/user/profile/41
Content-Type: application/json
    

###Get user profile by id
GET http://localhost:3001/user/profile/8


### Login with valid credentials
POST http://localhost:3001/user/login
Content-Type: application/json
    
{
        "email": "jon@doiia.com",
        "password": "joui86"
}

### Login with invalid credentials
POST http://localhost:3001/user/login
Content-Type: application/json
    
{
        "email": "admin@foo.com",
        "password": "admin"
}

### Register a new user
POST http://localhost:3001/user/register
Content-Type: application/json
    
{
        "firstname": "jane",
        "lastname": "ban",
        "phone": "1234555651",
        "email": "jane@ban.com",
        "image_name": "image.jpg",
        "password": "jane12"
}


### Feedback
POST http://localhost:3001/feedback
Content-Type: application/json
    
{
        "user_id": "2",
        "feedback_text": "I love the content",
        "satisfaction_rating": "5"

}

### Save Quiz Result
POST http://localhost:3001/myquizzes/saveQuizResult
Content-Type: application/json

{
    "user_id": 1,
    "cate_name": "Mathematics",
    "score": 5
}