### Send score details
POST http://localhost:3001/score
Content-Type: application/json

{
    "id_user":"11",
    "id_category":"2",
    "score": "8"
}

### Get score details
GET http://localhost:3001/score/4