###Get all users
GET http://localhost:3001/user



### Get user data
GET http://localhost:3001/user/profile/46
Content-Type: application/json
    

###Get user profile by id
GET http://localhost:3001/user/profile/8


### Login with valid credentials
POST http://localhost:3001/user/login
Content-Type: application/json
    
{
        "email": "admin@fo.com",
        "password": "admin1110"
}

### Login with invalid credentials
POST http://localhost:3001/user/login
Content-Type: application/json
    
{
        "email": "admin@foo.com",
        "password": "admin"
}

### Register a new user
POST http://localhost:3001/user/register
Content-Type: application/json
    
{
        "firstname": "gleo8ria",
        "lastname": "bediko",
        "phone": "1234578090",
        "email": "admin@f8oodi.gom",
        "password": "admin281110"
}



### Update user profile
PUT http://localhost:3001/user/profile/?id=46
Content-Type: application/json
    
{
        "firstname": "jane",
        "lasname": "joy",
        "phone" : "1234567899",
        "email": "ggg@gg.com"

}

### Feedback
POST http://localhost:3001/feedback
Content-Type: application/json
    
{
        "user_id": "1234",
        "email": "Hikko@gmail.com",
        "feedback_text": "I love the content",
        "satisfaction_rating": "5"

}

### Save Quiz Result
POST http://localhost:3001/myquizzes/saveQuizResult
Content-Type: application/json

{
    "user_id": 1,
    "cate_name": "Mathematics",
    "score": 5
}