###Get all users
GET http://localhost:3001/user



### Get user data
GET http://localhost:3001/user/profile/46
Content-Type: application/json
    

###Get user profile by id
GET http://localhost:3001/user/profile/2


### Login with valid credentials
POST http://localhost:3001/user/login
Content-Type: application/json
    
{
        "email": "jon@todi.com",
        "password": "joune4786"
}

### Login with invalid credentials
POST http://localhost:3001/user/login
Content-Type: application/json
    
{
        "email": "admin@foo.com",
        "password": "admin"
}

### Register a new user
POST http://localhost:3001/user/register
Content-Type: application/json
    
{
        "firstname": "Joupt",
        "lastname": "Junant",
        "phone": "1234585856",
        "email": "jon@todi.com",
        "image_name": "image6lt.jpg",
        "password": "joune4786"
}


### Feedback
POST http://localhost:3001/feedback
Content-Type: application/json
    
{
        "user_id": "2",
        "feedback_text": "I love the content",
        "satisfaction_rating": "5"

}

### Save Quiz Result
POST http://localhost:3001/myquizzes/saveQuizResult
Content-Type: application/json

{
    "user_id": 1,
    "cate_name": "Mathematics",
    "score": 5
}