##Get all users
GET http://localhost:3001


### Login with valid credentials
POST http://localhost:3001/user/login
Content-Type: application/json
    
{
        "email": "glory@info.com",
        "password": "glory123"
}

### Login with invalid credentials
POST http://localhost:3001/user/login
Content-Type: application/json
    
{
        "email": "admin@foo.com",
        "password": "admin"
}

### Register a new user
POST http://localhost:3001/user/register
Content-Type: application/json
    
{
        "email": "glory@info.com",
        "password": "glory123"
}